### ISSUE TITLE
Adding a game: Battleships

### ISSUE THREAD

**Issue by n0acar** [grantjenks/free-python-games#13]
I am a student that has experience in programming but not GitHub. So I want to start with something simple. Is it ok for me to contribute to your project with the game battleships

**Comment by grantjenks** [comment]
You are welcome to fork the project and create a game. I have a set of guidelines for games to be added:

http://www.grantjenks.com/docs/freegames/development.html

The most important thing is that the games be short, simple and fun. Anything over 80-100 lines of code probably won’t be included.

In the game of battleship, each player must keep their board secret. How would you do that for a two player game with only one screen?

**Comment by grantjenks** [comment]
Check out my other ideas in issue #3, #4, and #5
