### ISSUE TITLE
Support for pythonista on iOS?

### ISSUE THREAD

**Issue by JaminShanti** [grantjenks/free-python-games#15]
Getting this error:
stash: <class 'TypeError'>: setup() takes from 1 to 3 positional arguments but 5 were given

When I type python3 -m freegames.snake

**Comment by grantjenks** [comment]
Works for me... The only setup() call is to `turtle.setup`. Try this:

```
$ python3
Python 3.6.5 (default, Mar 29 2018, 15:37:32) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from turtle import *
>>> setup(400, 400, 400, 400)
```

That should open a Turtle graphics window. Does it work?

**Comment by JaminShanti** [comment]
Thanks for the reply. Setting up my Son's iPhone with pythonista and though your repo would be a great start.

Getting this from the console:


>>> help(turtle.setup())
Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __hash__(...)
 |      x.__hash__() <==> hash(x)
 |  
 |  __repr__(...)
 |      x.__repr__() <==> repr(x)

**Comment by grantjenks** [comment]
Try `help(turtle.setup)` instead.

**Comment by JaminShanti** [comment]
Pythonista doesn't support turtle.  Sry and thank you for your time.

**Comment by grantjenks** [comment]
Bummer. Certainly would’ve been cool!
