### ISSUE TITLE
Typo in Snake.py

### ISSUE THREAD

**Issue by Requiem53** [grantjenks/free-python-games#24]
The word "exercises" in snake.py is misspelled as "excercises'

(This is my very first time "contributing" to GitHub. I'm fairly new to programming and I decided to start with Python. I'm very lucky to have discovered freegames!)

**Comment by grantjenks** [comment]
Good catch. Probably worthwhile to run a spellchecker over all the comments.

**Comment by grantjenks** [comment]
Fixed at c396e18
