### ISSUE TITLE
Add function : snake.py

### ISSUE THREAD

**Issue by Ahnsanghyun-hi** [grantjenks/free-python-games#25]
Added red dot.
Red dot is trash.
If the snake eat trash, it will be reduced in length by one.
If snake meet trash when len(snake) == 1, the game ends

And If the game is over, IDLE will print out 'Game End'.

https://github.com/grantjenks/free-python-games/pull/26

This is code.

**Comment by grantjenks** [comment]
Good exercise but I would rather keep the game simple.
