### ISSUE TITLE
Add Game: Rock, Paper, Scissors

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/free-python-games#4]
Prototype at https://code.activestate.com/recipes/578983-rockpaperscissors/

**Comment by grantjenks** [comment]
See pull #10

**Comment by danderson2794** [comment]
Since this is still open, I'll create the Rock Paper Scissors game. Are you wanting a GUI or strictly through command line?

**Comment by grantjenks** [comment]
I want it to be a GUI that listens for key presses. I imagine a countdown: 3, 2, 1 then like a 0.25 second window for key presses. Two player game. Key presses decide outcome. If the key press does t occur then it should be displayed somehow. I want to discourage cheating.

Check out the Simon Says game for an animation example. I’m not sure how to represent rock, paper, and scissors. Maybe rock is a circle, paper is a square and scissors is a V. Then misfire can be a dash. Then there should be a table of outcomes. Such as:

1, 2
Rock, Rock, tie
Rock, Scissor, 1
Rock, Paper, 2
Rock, Dash, 1
...

Does that make sense?

**Comment by grantjenks** [comment]
Also, check out the development notes at http://www.grantjenks.com/docs/freegames/development.html

**Comment by danderson2794** [comment]
Yeah, that makes sense, but what if we didn't have the count down and generated a random choice by the computer after the user selected either rock, paper, or scissors, that way the user experience is consistent. Also, I noticed you use Turtle for the other projects, would you mind if I used PyGame?

**Comment by grantjenks** [comment]
The one player version sounds good. I think the countdown would still be fun but it’s fine to start without.

Turtle is a must. It’s more beginner friendly.

**Comment by luminate22** [comment]
Is this issue still open?
