### ISSUE TITLE
there is no module called as freegames... and the code will shows an module error .

### ISSUE THREAD

**Issue by kotreshtvheremath** [grantjenks/free-python-games#43]

**Comment by grantjenks** [comment]
Sounds like it’s not properly installed then.

**Comment by navinofficial** [comment]
Hi, 
I am facing the same issue . 
Please let me know the solution if you have figured it out .
Thank you.

**Comment by grantjenks** [comment]
You must install the package to run the games. See the QuickStart section at http://www.grantjenks.com/docs/freegames/ and run “python3 -m pip install freegames”

**Comment by navinofficial** [comment]
Hello . 
I have installed this module (freegames) using pip3 install freegames and also have installed pygame. 
And it's in /opt/homebrew/lib/python3.9/site-packages (2.3.2)
I have also checked using pip freeze . 

But the python2.7 is in library/framework/python.framework/python2.7 

I can't move it there , and I cannot find a solution yet . Can you please help. 

Thank you.

**Comment by sashwatkoirala** [comment]
me too i am facing the same issue

**Comment by grantjenks** [comment]
Try this:

Open a new terminal or console window

python3 -m pip install freegames

python3 -m freegames
