### ISSUE TITLE
Support for object-oriented programming courses

### ISSUE THREAD

**Issue by adorilson** [grantjenks/free-python-games#52]
Hi.

I'm a professor and I'm starting to tutor students to implement OOP version games.
(Recently, [we receive a donation to this initiative](https://portal.ifrn.edu.br/campus/ceara-mirim/noticias/projeto-do-campus-ceara-mirim-recebe-incentivo-de-profissional-do-desenvolvimento-de-software-nacional) - in pt-br)

We not intend to change the current files, but just add new files (rewriting some games)  in this programming paradigm.
So FPG would can be used in OOP courses, too.

A initial idea is add a new folder, called oop, where these new files will live.
So, if you want copy the snake game in a oop approach, you just type

```
$ python3 -m freegames copy oop.snake
$ python3 snake.py
```

What do you think about?  Some comment? Some preference for what game we can start?

**Comment by grantjenks** [comment]
I'm open to it. But I can't help much. Go ahead and start with some pull requests.

If my replies are too delayed or you want to go a different direction then you're free to fork the project and publish to PyPI as freegamesoop (for example). (Others have done this.)
