### ISSUE TITLE
[guess.py] - add and display counter to guesses upon game ending

### ISSUE THREAD

**Issue by drocpdp** [grantjenks/free-python-games#64]
When user completes game successfully, display message displaying number of guesses it took to complete.
Include tests.

Message will be:
(if guesses > 1)
Congratulations! You guessed the right answer:[value]
It took you [number of guesses] guesses! 

(if guesses == 1)
Congratulations! You guessed the right answer:[value]
It took you 1 guess!

**Comment by drocpdp** [comment]
If this issue is feasible, could you kindly assign to me? :-)

**Comment by grantjenks** [comment]
Printing the number of guesses is already one of the suggested exercises at the top.
