### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by partypiotr** [grantjenks/free-python-games#67]
When i try to run bounce.py it says there is no module called freegames
![Zrzut ekranu 2021-06-23 073228](https://user-images.githubusercontent.com/64352322/123041150-37b52a00-d3f5-11eb-9114-9e0121d8a1cd.png)

**Comment by grantjenks** [comment]
You must install the package to run the games. See the QuickStart section at http://www.grantjenks.com/docs/freegames/ and run “python3 -m pip install freegames”
